CREATE TABLE vendedor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)    NOT NULL,
    email           VARCHAR(150)    NOT NULL UNIQUE,
    regiao          VARCHAR(120)    NOT NULL,
    ativo           BOOLEAN         NOT NULL DEFAULT TRUE,
    data_criacao    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
