CREATE TABLE cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)    NOT NULL,
    propriedade     VARCHAR(150),
    cultura         VARCHAR(100),
    municipio       VARCHAR(100),
    telefone        VARCHAR(30),
    email           VARCHAR(150),
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDENTE',
    qualificado     BOOLEAN         NOT NULL DEFAULT FALSE,
    vendedor_id     BIGINT          REFERENCES vendedor(id),
    arquivo_importado_id BIGINT,
    data_criacao    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cliente_status ON cliente(status);
CREATE INDEX idx_cliente_vendedor ON cliente(vendedor_id);
