CREATE TABLE qualificacao_cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    aprovado        BOOLEAN         NOT NULL,
    motivo_rejeicao VARCHAR(255),
    qualificado_por VARCHAR(150),
    data_qualificacao TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_qualificacao_cliente ON qualificacao_cliente(cliente_id);
