CREATE TABLE oportunidade (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    vendedor_id     BIGINT          REFERENCES vendedor(id),
    descricao       VARCHAR(255)    NOT NULL,
    valor_estimado  DECIMAL(14,2),
    status          VARCHAR(20)     NOT NULL DEFAULT 'ABERTA',
    data_criacao    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
