CREATE TABLE contato_cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    vendedor_id     BIGINT          REFERENCES vendedor(id),
    canal           VARCHAR(30)     NOT NULL DEFAULT 'TELEFONE',
    observacao      VARCHAR(500),
    data_contato    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_contato_cliente ON contato_cliente(cliente_id);
