CREATE TABLE retorno_agendado (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    vendedor_id     BIGINT          NOT NULL REFERENCES vendedor(id),
    data_agendada   TIMESTAMP       NOT NULL,
    concluido       BOOLEAN         NOT NULL DEFAULT FALSE,
    observacao      VARCHAR(500),
    data_criacao    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agenda_vendedor ON retorno_agendado(vendedor_id);
