CREATE TABLE venda (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    vendedor_id     BIGINT          NOT NULL REFERENCES vendedor(id),
    valor           DECIMAL(14,2)   NOT NULL,
    observacao      VARCHAR(500),
    data_venda      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_venda_vendedor ON venda(vendedor_id);
