CREATE TABLE arquivo_importado (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo        VARCHAR(255)    NOT NULL,
    linhas_lidas        INT             NOT NULL DEFAULT 0,
    linhas_validas      INT             NOT NULL DEFAULT 0,
    linhas_com_erro     INT             NOT NULL DEFAULT 0,
    status              VARCHAR(30)     NOT NULL DEFAULT 'AGUARDANDO_VALIDACAO',
    data_importacao     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE cliente ADD CONSTRAINT fk_cliente_arquivo_importado
    FOREIGN KEY (arquivo_importado_id) REFERENCES arquivo_importado(id);
