CREATE TABLE log_importacao (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo_importado_id    BIGINT          NOT NULL REFERENCES arquivo_importado(id),
    linha                   INT             NOT NULL,
    mensagem_erro           VARCHAR(500)    NOT NULL
);

CREATE INDEX idx_log_arquivo ON log_importacao(arquivo_importado_id);
