CREATE TABLE usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)    NOT NULL,
    username        VARCHAR(100)    NOT NULL UNIQUE,
    senha           VARCHAR(255)    NOT NULL,
    perfil          VARCHAR(20)     NOT NULL DEFAULT 'GERENTE',
    ativo           BOOLEAN         NOT NULL DEFAULT TRUE
);
