-- Registrado automaticamente quando o vendedor abre a ficha de um cliente (item 4 / obs.)
CREATE TABLE log_produtividade (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendedor_id     BIGINT          NOT NULL REFERENCES vendedor(id),
    cliente_id      BIGINT          NOT NULL REFERENCES cliente(id),
    tipo_atividade  VARCHAR(50)     NOT NULL,
    observacao      VARCHAR(500),
    data_hora       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_logprod_vendedor  ON log_produtividade(vendedor_id);
CREATE INDEX idx_logprod_cliente   ON log_produtividade(cliente_id);
CREATE INDEX idx_logprod_data      ON log_produtividade(data_hora);
