-- Auditoria geral: toda alteração confirmada por senha é registrada aqui (item 7.2)
CREATE TABLE log_sistema (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT          NOT NULL REFERENCES usuario(id),
    acao        VARCHAR(80)     NOT NULL,
    entidade    VARCHAR(60)     NOT NULL,
    entidade_id BIGINT,
    detalhes    VARCHAR(2000),
    ip          VARCHAR(45),
    data_hora   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_logsistema_usuario ON log_sistema(usuario_id);
CREATE INDEX idx_logsistema_data    ON log_sistema(data_hora);
